using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace Toybox.Studio.Generators;

/// <summary>
/// Writes one synced class's generated partial: the injected <c>EngineObject</c> base, per-property
/// slots/fields/implementations, the inbound <c>Apply</c>/<c>WireKeyFor</c>/<c>WriteExtras</c>
/// overrides, method bodies as engine commands, and relay command wrappers.
/// </summary>
internal static class SyncClassEmitter
{
    private const string EngineObject = "global::Toybox.Studio.EngineApi.EngineObject";
    private const string EngineAddress = "global::Toybox.Studio.EngineApi.EngineAddress";
    private const string SyncSlot = "global::Toybox.Studio.EngineApi.SyncSlot";
    private const string SyncMode = "global::Toybox.Studio.EngineApi.SyncMode";
    private const string JToken = "global::Newtonsoft.Json.Linq.JToken";
    private const string JObject = "global::Newtonsoft.Json.Linq.JObject";
    private const string ResultTask = "global::System.Threading.Tasks.Task<global::Toybox.Studio.Utils.Result>";
    private const string NoToken = "global::System.Threading.CancellationToken.None";
    private const string AsyncRelayCommand = "global::CommunityToolkit.Mvvm.Input.AsyncRelayCommand";
    private const string IAsyncRelayCommand = "global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand";

    public static string Emit(SyncedClass model)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated by Toybox.Studio.Generators.EngineSyncGenerator/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        if (model.Namespace.Length > 0)
        {
            source.Append("namespace ").Append(model.Namespace).AppendLine(";");
            source.AppendLine();
        }

        source.Append("partial class ").Append(model.Name).Append(model.TypeParameters);
        if (model.InjectBase)
            source.Append(" : ").Append(EngineObject);
        source.AppendLine();
        source.AppendLine("{");

        EmitFields(source, model);
        EmitProperties(source, model);
        EmitMethods(source, model);
        EmitApply(source, model);
        EmitCollectInto(source, model);
        EmitWireKeyFor(source, model);
        EmitWriteExtras(source, model);

        TrimTrailingBlank(source);
        source.AppendLine("}");
        return source.ToString();
    }

    private static void EmitFields(StringBuilder source, SyncedClass model)
    {
        foreach (var property in model.Properties.Where(property => property.ConverterDisplay is not null))
            source.Append("    private static readonly ").Append(property.ConverterDisplay).Append(' ')
                .Append(property.ConverterFieldName).AppendLine(" = new();");

        foreach (var property in model.Properties)
        {
            source.Append("    private static readonly ").Append(SyncSlot).Append(' ')
                .Append(property.SlotName).AppendLine(" = new(");
            source.Append("        ").Append(Quote(property.Command)).AppendLine(",");
            source.Append("        ").Append(Quote(property.Key)).AppendLine(",");
            source.Append("        ").Append(SyncMode).Append('.').Append(property.Mode).AppendLine(",");
            source.Append("        ").Append(property.BatchFrequencyMs.ToString(CultureInfo.InvariantCulture))
                .AppendLine(",");
            source.Append("        static value => ").Append(property.WriteCall).AppendLine(",");
            source.Append("        static token => ").Append(property.ReadCall).AppendLine(");");
        }

        if (model.Properties.Count > 0)
            source.AppendLine();

        foreach (var property in model.Properties)
        {
            source.Append("    private ").Append(property.TypeDisplay).Append(' ').Append(property.FieldName);
            if (property.IsReferenceType && !property.TypeDisplay.EndsWith("?", System.StringComparison.Ordinal))
                source.Append(" = default!");
            source.AppendLine(";");
        }

        foreach (var method in model.Methods.Where(method => method.Relay))
            source.Append("    private ").Append(RelayCommandType(method, iface: false))
                .Append("? ").Append(RelayFieldName(method)).AppendLine(";");

        if (model.Properties.Count > 0 || model.Methods.Any(method => method.Relay))
            source.AppendLine();
    }

    private static void EmitProperties(StringBuilder source, SyncedClass model)
    {
        foreach (var property in model.Properties)
        {
            if (!property.HasSetter)
            {
                source.Append("    ").Append(property.Accessibility).Append(" partial ")
                    .Append(property.TypeDisplay).Append(' ').Append(property.Name)
                    .Append(" => ").Append(property.FieldName).AppendLine(";");
                source.AppendLine();
                continue;
            }

            // A Mirror setter still routes through Push — it only ever applies locally, since the
            // scheduler is never handed a Mirror slot.
            source.Append("    ").Append(property.Accessibility).Append(" partial ")
                .Append(property.TypeDisplay).Append(' ').AppendLine(property.Name);
            source.AppendLine("    {");
            source.Append("        get => ").Append(property.FieldName).AppendLine(";");
            source.Append("        ").Append(property.SetterModifier).Append("set => Push(ref ")
                .Append(property.FieldName).Append(", value, ").Append(property.SlotName).AppendLine(");");
            source.AppendLine("    }");
            source.AppendLine();
        }

        foreach (var method in model.Methods.Where(method => method.Relay))
        {
            source.Append("    public ").Append(RelayCommandType(method, iface: true)).Append(' ')
                .Append(method.CommandPropertyName).AppendLine(" =>");
            source.Append("        ").Append(RelayFieldName(method)).Append(" ??= new ")
                .Append(RelayCommandType(method, iface: false)).Append('(')
                .Append(RelayLambda(method)).AppendLine(");");
            source.AppendLine();
        }

        if (model.AddressExpression is { } address)
        {
            source.Append("    protected override ").Append(EngineAddress).Append(" Address => new(")
                .Append(address).AppendLine(");");
            source.AppendLine();
        }
    }

    private static void EmitMethods(StringBuilder source, SyncedClass model)
    {
        foreach (var method in model.Methods)
        {
            var parameters = string.Join(
                ", ",
                method.Parameters.Select(parameter => parameter.TypeDisplay + " " + parameter.Name));
            source.Append("    ").Append(method.Accessibility).Append(" partial ").Append(ResultTask)
                .Append(' ').Append(method.Name).Append('(').Append(parameters).AppendLine(")");
            source.AppendLine("    {");
            source.Append("        var payload = ")
                .AppendLine(model.IsRooted ? "CreatePayload();" : $"new {JObject}();");
            foreach (var extra in method.Extras)
                source.Append("        payload[").Append(Quote(extra.Key)).Append("] = ")
                    .Append(extra.ValueExpression).AppendLine(";");
            foreach (var parameter in method.PayloadParameters)
                source.Append("        payload[").Append(Quote(parameter.Key)).Append("] = ")
                    .Append(parameter.WriteCall).AppendLine(";");
            var send = model.IsRooted ? "SendCommandAsync" : model.EngineMemberName + ".SendCommandAsync";
            source.Append("        return ").Append(send).Append('(').Append(Quote(method.Command))
                .Append(", payload, ").Append(method.CancellationTokenName ?? NoToken).AppendLine(");");
            source.AppendLine("    }");
            source.AppendLine();
        }
    }

    private static void EmitApply(StringBuilder source, SyncedClass model)
    {
        if (model.Properties.Count == 0)
            return;

        source.Append("    protected override bool Apply(string key, ").Append(JToken).AppendLine(" value)");
        source.AppendLine("    {");
        source.AppendLine("        switch (key)");
        source.AppendLine("        {");
        foreach (var property in model.Properties)
        {
            source.Append("            case ").Append(Quote(property.Key)).AppendLine(":");
            source.Append("                Hydrate(ref ").Append(property.FieldName).Append(", value, ")
                .Append(property.SlotName).AppendLine(");");
            source.AppendLine("                return true;");
        }

        source.AppendLine("            default:");
        source.AppendLine("                return base.Apply(key, value);");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
    }

    // Serialize()'s per-class contribution: every synced value except Mirror ones — those are
    // engine-owned (ids and the like), and a copied body must carry content, never identity.
    private static void EmitCollectInto(StringBuilder source, SyncedClass model)
    {
        var serialized = model.Properties.Where(property => !property.IsMirror).ToList();
        if (serialized.Count == 0)
            return;

        source.Append("    protected override void CollectInto(").Append(JObject).AppendLine(" body)");
        source.AppendLine("    {");
        source.AppendLine("        base.CollectInto(body);");
        foreach (var property in serialized)
            source.Append("        body[").Append(Quote(property.Key)).Append("] = ")
                .Append(property.SlotName).Append(".Write(").Append(property.Name).AppendLine(");");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void EmitWireKeyFor(StringBuilder source, SyncedClass model)
    {
        if (model.Properties.Count == 0)
            return;

        source.AppendLine("    protected override string? WireKeyFor(string propertyName) => propertyName switch");
        source.AppendLine("    {");
        foreach (var property in model.Properties)
            source.Append("        ").Append(Quote(property.Name)).Append(" => ")
                .Append(Quote(property.Key)).AppendLine(",");
        source.AppendLine("        _ => base.WireKeyFor(propertyName),");
        source.AppendLine("    };");
        source.AppendLine();
    }

    private static void EmitWriteExtras(StringBuilder source, SyncedClass model)
    {
        var withExtras = model.Properties.Where(property => property.Extras.Count > 0).ToList();
        if (withExtras.Count == 0)
            return;

        source.Append("    protected override void WriteExtras(string key, ").Append(JObject)
            .AppendLine(" payload)");
        source.AppendLine("    {");
        source.AppendLine("        base.WriteExtras(key, payload);");
        source.AppendLine("        switch (key)");
        source.AppendLine("        {");
        foreach (var property in withExtras)
        {
            source.Append("            case ").Append(Quote(property.Key)).AppendLine(":");
            foreach (var extra in property.Extras)
                source.Append("                payload[").Append(Quote(extra.Key)).Append("] = ")
                    .Append(extra.ValueExpression).AppendLine(";");
            source.AppendLine("                break;");
        }

        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static string RelayCommandType(SyncedMethod method, bool iface)
    {
        var name = iface ? IAsyncRelayCommand : AsyncRelayCommand;
        var value = method.PayloadParameters.FirstOrDefault();
        return value is null ? name : name + "<" + value.TypeDisplay + ">";
    }

    private static string RelayLambda(SyncedMethod method)
    {
        var value = method.PayloadParameters.FirstOrDefault();
        var ct = method.CancellationTokenName;
        return (value, ct) switch
        {
            (null, null) => $"() => {method.Name}()",
            (null, not null) => $"ct => {method.Name}(ct)",
            (not null, null) => $"value => {method.Name}(value!)",
            _ => $"(value, ct) => {method.Name}(value!, ct)",
        };
    }

    private static string RelayFieldName(SyncedMethod method) =>
        "_" + char.ToLowerInvariant(method.CommandPropertyName[0]) + method.CommandPropertyName.Substring(1);

    private static string Quote(string text) => "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    // Collapses however many blank lines the section emitters left at the end into exactly one newline.
    private static void TrimTrailingBlank(StringBuilder source)
    {
        while (source.Length > 0 && (source[source.Length - 1] == '\n' || source[source.Length - 1] == '\r'))
            source.Length--;
        source.AppendLine();
    }
}
