using System.Diagnostics;
using System.Text;
using Toybox.Studio.Coding;
using Toybox.Studio.Monaco;
using Toybox.Studio.Utils;

namespace Toybox.Studio.Coding.Languages;

/// <summary>
/// Launches clangd for C++ (and its headers), pointed at the project's <c>compile_commands.json</c> with
/// background indexing so completion / go-to-definition / diagnostics span the engine headers and every sibling
/// script. Seeds a project <c>.clangd</c> so script translation units — which the project build doesn't export
/// into <c>compile_commands.json</c> — still resolve the engine's and the scripts' generated headers. When no
/// compile database is present it still starts (headers resolve via <c>.clangd</c>), and it says so in the log,
/// since full project-wide C++ IntelliSense needs a Ninja/clang build to emit <c>compile_commands.json</c>.
/// </summary>
public sealed class ClangdServerFactory : ILanguageServerFactory
{
    public IReadOnlyList<string> LanguageIds { get; } = [ScriptLanguages.Cpp.Id];

    public Result<ILanguageServer?> Start(MonacoSession session, LanguageServerContext context)
    {
        var located = ClangdLocator.Locate();
        if (!located)
            return Result<ILanguageServer?>.Ok(null); // clangd not installed: highlight-only, caller logs.

        EnsureConfig(context);

        var info = new ProcessStartInfo
        {
            FileName = located.Value!,
            WorkingDirectory = context.ProjectRoot,
            RedirectStandardInput = true,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
            StandardOutputEncoding = Encoding.UTF8,
            StandardErrorEncoding = Encoding.UTF8,
        };
        info.ArgumentList.Add("--background-index");
        info.ArgumentList.Add("--pch-storage=memory");
        info.ArgumentList.Add("--limit-results=100");
        info.ArgumentList.Add("--log=error");

        var compileCommandsDir = CompileCommandsDir(context.ProjectRoot);
        if (compileCommandsDir is { })
            info.ArgumentList.Add($"--compile-commands-dir={compileCommandsDir}");
        else
            context.Log.Info(
                "Code editor: no compile_commands.json for this project — C++ IntelliSense resolves engine "
                + "headers via .clangd, but full project-wide analysis needs a clang/Ninja build to emit one.");

        Process process;
        try
        {
            process = Process.Start(info) ?? throw new InvalidOperationException("Process.Start returned null.");
        }
        catch (Exception e)
        {
            return Result<ILanguageServer?>.Fail($"Couldn't start clangd: {e.Message}");
        }

        var server = new StdioLspServer("clangd", LanguageIds, session, process, context.Log, "clangd");
        session.EnableLsp("clangd", new Uri(context.ProjectRoot).AbsoluteUri, LanguageIds);
        return Result<ILanguageServer?>.Ok(server);
    }

    // Marks our generated .clangd so we can upgrade it when the template changes without clobbering a config the
    // user wrote themselves. Bump when the flag set below changes.
    private const string ConfigMarker = "# Generated by Toybox Studio for the code editor";

    // Writes a project .clangd so script translation units — which the project build doesn't export into
    // compile_commands.json — still resolve their headers: the engine source roots, the engine's and the
    // script's GENERATED headers, plus -Wno-unknown-attributes and a generated/inl diagnostics ignore. Only
    // (re)written when absent or when the existing file is our own earlier generated one.
    private static void EnsureConfig(LanguageServerContext context)
    {
        var path = Path.Combine(context.ProjectRoot, ".clangd");
        if (File.Exists(path) && !IsStudioGenerated(path))
            return; // The user wrote their own — leave it.

        var add = new List<string> { "-std=c++23", "-Wno-unknown-attributes" };
        if (context.EngineRoot is not null)
        {
            var root = context.EngineRoot.Replace('\\', '/').TrimEnd('/');
            add.Add($"-I{root}/engine/include");
        }

        foreach (var dir in GeneratedIncludeDirs(Path.Combine(context.ProjectRoot, "build")))
            add.Add($"-I{dir.Replace('\\', '/')}");

        var lines = new List<string>
        {
            $"{ConfigMarker}. Safe to edit or delete.",
            "CompileFlags:",
            "  Add:",
        };
        lines.AddRange(add.Select(flag => $"    - {flag}"));
        lines.Add("Diagnostics:");
        lines.Add("  Includes:");
        lines.Add("    IgnoreHeader:");
        lines.Add("      - '.*\\.generated\\.h'");
        lines.Add("      - '.*\\.inl'");

        try
        {
            File.WriteAllText(path, string.Join("\n", lines) + "\n");
            context.Log.Info($"Code editor: wrote {path} for clangd include resolution.");
        }
        catch (Exception e)
        {
            context.Log.Warning($"Code editor: couldn't write .clangd: {e.Message}");
        }
    }

    private static bool IsStudioGenerated(string path)
    {
        try
        {
            using var reader = new StreamReader(path);
            return reader.ReadLine()?.StartsWith(ConfigMarker, StringComparison.Ordinal) == true;
        }
        catch (Exception)
        {
            return false;
        }
    }

    // The codegen output directories under the build tree that hold the generated headers script and engine
    // sources include (the script's <name>.generated.h in a generated/scripts folder; the engine's
    // tbx/.../<x>.generated.h under engine's generated/include).
    private static IEnumerable<string> GeneratedIncludeDirs(string buildDir)
    {
        string[] candidates =
        [
            Path.Combine(buildDir, "engine", "engine", "generated", "include"),
            Path.Combine(buildDir, "generated", "scripts"),
            Path.Combine(buildDir, "Scripts", "generated", "scripts"),
            Path.Combine(buildDir, "Source", "Scripts", "generated", "scripts"),
        ];

        foreach (var dir in candidates)
            if (Directory.Exists(dir))
                yield return dir;
    }

    // clangd reads compile_commands.json from this directory; prefer the project's build/ folder, then root.
    private static string? CompileCommandsDir(string projectRoot)
    {
        foreach (var dir in new[] { Path.Combine(projectRoot, "build"), projectRoot })
        {
            if (File.Exists(Path.Combine(dir, "compile_commands.json")))
                return dir;
        }

        return null;
    }
}
